- ansible.builtin.import_playbook: "playbook_bastion.yaml"
- ansible.builtin.import_playbook: "playbook_server.yaml"
- ansible.builtin.import_playbook: "playbook_client.yaml"
- ansible.builtin.import_playbook: "playbook_lb.yaml"
