# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

- hosts: client
  roles:
    - role: hashicorp.nomad_bench.common

    - role: hashicorp.nomad_bench.cni

    - role: "geerlingguy.docker"
      become: true

    - role: hashicorp.nomad_bench.nomad
      vars:
        nomad_client_enabled: true
        nomad_server_join_retry_join: ["{{ terraform_nomad_server_join }}"]
        nomad_telemetry_publish_allocation_metrics: true
        nomad_telemetry_publish_node_metrics: true
        nomad_tls_enable: true
        nomad_tls_ca_cert: "{{ lookup('file', '../tls/nomad-agent-ca.pem') }}"
        nomad_tls_cert: "{{ lookup('file', '../tls/global-client-nomad.pem') }}"
        nomad_tls_cert_key: "{{ lookup('file', '../tls/global-client-nomad-key.pem') }}"
        nomad_plugins:
          docker:
            config:
              allow_privileged: true
              volumes:
                enabled: true
          raw_exec:
            config:
              enabled: true
        nomad_acl_enabled: true

    - role: hashicorp.nomad_bench.influxdb_telegraf
      vars:
        influxdb_telegraf_input_nomad_url: "https://127.0.0.1:4646"
        influxdb_telegraf_input_nomad_tls_ca: "{{ nomad_config_dir }}tls/ca.pem"
        influxdb_telegraf_output_token: "{{ terraform_influxdb_token }}"
        influxdb_telegraf_output_organization: "nomad-eng"
        influxdb_telegraf_output_bucket: "{{ terraform_project_name }}"
        # Hack to make the Terraform dynamic inventory plugin work with complex types.
        influxdb_telegraf_output_urls: "{{ terraform_influxdb_telegraf_output_urls_json | ansible.builtin.from_json }}"
