# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

roles:
  - src: "geerlingguy.docker"
    version: "7.1.0"
  - src: "gantsign.golang"
    version: "3.2.4"

collections:
  - name: "cloud.terraform"
    version: "2.0.0"
