- name: "create_tls_directory"
  become: true
  ansible.builtin.file:
    path: "{{ nomad_config_dir }}/tls"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    state: "directory"
    mode: "0711"

- name: "write_tls_files"
  become: true
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0644"
  loop:
    - dest: "{{ nomad_config_dir }}tls/ca.pem"
      content: "{{ nomad_tls_ca_cert }}"
    - dest: "{{ nomad_config_dir }}tls/cert.pem"
      content: "{{ nomad_tls_cert }}"
    - dest: "{{ nomad_config_dir }}tls/cert-key.pem"
      content: "{{ nomad_tls_cert_key }}"

- name: "create_tls_config_file"
  become: true
  ansible.builtin.template:
    src: "tls.hcl.j2"
    dest: "{{ nomad_config_dir }}/tls.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0655"
  notify:
    - "restart_nomad"

- name: "create_nomad_cli_profile"
  become: true
  ansible.builtin.template:
    src: "nomad_profile.sh.j2"
    dest: "/etc/profile.d/nomad.sh"
    owner: "root"
    group: "root"
    mode: "0755"
  when: nomad_cli_profile_enabled is true

- name: "write_cli_tls_files"
  become: true
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0644"
  when: nomad_cli_profile_enabled is true
  loop:
    - dest: "{{ nomad_config_dir }}/tls/cli.pem"
      content: "{{ nomad_cli_tls_cert }}"
    - dest: "{{ nomad_config_dir }}/tls/cli-key.pem"
      content: "{{ nomad_cli_tls_cert_key }}"
