- hosts: client
  roles:
    - role: "geerlingguy.docker"
      become: true

    - role: cni

    - role: nomad
      vars:
        nomad_host_volumes:
          - name: influxdb
            path: /opt/influxdb
            read_only: false
