- hosts: client
  roles:
    - role: cni

    - role: nomad
      vars:
        nomad_tls_enable: true
        nomad_tls_ca_cert: "{{ lookup('file', '../terraform/control/eu-west-2/core/tls/nomad-agent-ca.pem') }}"
        nomad_tls_cert: "{{ lookup('file', '../terraform/control/eu-west-2/core/tls/global-client-nomad.pem') }}"
        nomad_tls_cert_key: "{{ lookup('file', '../terraform/control/eu-west-2/core/tls/global-client-nomad-key.pem') }}"
        nomad_host_volumes:
          - name: influxdb
            path: /opt/influxdb
            read_only: false
