- hosts: core_server
  roles:
    - role: influxdb_telegraf
      influxdb_telegraf_input_nomad_url: "http://127.0.0.1:4646"
      influxdb_telegraf_output_urls: [ "http://10.0.4.237:23942" ]
      influxdb_telegraf_output_token: "ZuXY8FXZL435F7TXeiA_UUOnx4cA4pCqDfsbYyW9O9eysFeR_5SmcNS8ZKb35FtG50ul4WIxAz9RksGt6fb1og=="
      influxdb_telegraf_output_organization: "nomad-eng"
      influxdb_telegraf_output_bucket: "default"
