- hosts: core_server
  roles:
    - role: nomad
      vars:
        nomad_tls_enable: true
        nomad_tls_ca_cert: "{{ lookup('file', '../terraform/control/eu-west-2/core/tls/nomad-agent-ca.pem') }}"
        nomad_tls_cert: "{{ lookup('file', '../terraform/control/eu-west-2/core/tls/global-server-nomad.pem') }}"
        nomad_tls_cert_key: "{{ lookup('file', '../terraform/control/eu-west-2/core/tls/global-server-nomad-key.pem') }}"
        nomad_cli_profile_enabled: true
        nomad_cli_tls_cert: "{{ lookup('file', '../terraform/control/eu-west-2/core/tls/global-cli-nomad.pem') }}"
        nomad_cli_tls_cert_key: "{{ lookup('file', '../terraform/control/eu-west-2/core/tls/global-cli-nomad-key.pem') }}"

    - role: influxdb_telegraf
      vars:
        influxdb_telegraf_input_nomad_url: "http://127.0.0.1:4646"
        influxdb_telegraf_output_urls: [ "http://10.0.4.237:23942" ]
        influxdb_telegraf_output_token: "ZuXY8FXZL435F7TXeiA_UUOnx4cA4pCqDfsbYyW9O9eysFeR_5SmcNS8ZKb35FtG50ul4WIxAz9RksGt6fb1og=="
        influxdb_telegraf_output_organization: "nomad-eng"
        influxdb_telegraf_output_bucket: "default"
