- hosts: client
  roles:
    - role: common

    - role: cni

    - role: "geerlingguy.docker"
      become: true

    - role: nomad
      vars:
        nomad_tls_enable: true
        nomad_tls_ca_cert: "{{ lookup('file', '../terraform/control/{{ ansible_ec2_placement_region }}/{{ project_name }}/tls/nomad-agent-ca.pem') }}"
        nomad_tls_cert: "{{ lookup('file', '../terraform/control/{{ ansible_ec2_placement_region }}/{{ project_name }}/tls/{{ nomad_region }}-client-nomad.pem') }}"
        nomad_tls_cert_key: "{{ lookup('file', '../terraform/control/{{ ansible_ec2_placement_region }}/{{ project_name }}/tls/{{ nomad_region }}-client-nomad-key.pem') }}"
        nomad_host_volumes:
          - name: influxdb
            path: /opt/influxdb
            read_only: false
