# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

cni_plugins_path: "/opt/cni/bin"
cni_plugins_version: "1.3.0"

cni_plugins_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"

cni_plugins_url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-{{ ansible_system | lower }}-{{ cni_plugins_arch_map[ansible_architecture] }}-v{{ cni_plugins_version }}.tgz"
