- name: "write_tls_files"
  become: true
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0644"
  when: nomad_cli_profile_enabled is true
  loop:
    - dest: "{{ nomad_config_dir }}/tls/cli.pem"
      content: "{{ nomad_cli_tls_cert }}"
    - dest: "{{ nomad_config_dir }}/tls/cli-key.pem"
      content: "{{ nomad_cli_tls_cert_key }}"

- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: latest

- name: "create_nginx_lb_config"
  become: true
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/sites-available/default"
    owner: root
    group: root
    mode: "0644"
  notify:
    - "restart_nginx"