# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

nomad_version: "1.8.0-rc.1"

nomad_release_arch_map:
  amd64: "amd64"
  x86_64: "amd64"
  armv7l: "arm"
  aarch64: "arm64"
  32-bit: "386"
  64-bit: "amd64"

nomad_release_architecture: "{{ nomad_release_arch_map[ansible_architecture] }}"
nomad_release_zip_url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_{{ nomad_release_architecture }}.zip"
nomad_checksum_file_url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_SHA256SUMS"
nomad_package_name: "nomad_{{ nomad_version }}_linux_{{ nomad_release_architecture }}.zip"

nomad_user: root
nomad_group: root
nomad_config_dir: "/etc/nomad.d/"
nomad_config_extra: ""

nomad_install_dir: "/usr/bin"
nomad_custom_binary_source: ""

nomad_region: "global"
nomad_data_dir: "/opt/nomad/data"
nomad_log_level: "DEBUG"
nomad_log_json: true
nomad_log_include_location: true
nomad_log_file: "/var/log/nomad.log"
nomad_enable_debug: false

nomad_server_enabled: false
nomad_server_bootstrap_expect: 3

nomad_client_enabled: false

nomad_host_volumes: [ ]
nomad_plugins: {}

nomad_server_join_retry_join: [ ]
nomad_server_join_retry_max: 0
nomad_server_join_retry_interval: "30s"

nomad_limits_https_handshake_timeout: "5s"
nomad_limits_http_max_conns_per_client: 100
nomad_limits_rpc_handshake_timeout: "5s"
nomad_limits_rpc_max_conns_per_client: 100

nomad_telemetry_publish_allocation_metrics: false
nomad_telemetry_publish_node_metrics: false
nomad_telemetry_prometheus_metrics: false
nomad_telemetry_in_memory_collection_interval: ""
nomad_telemetry_in_memory_retention_period: ""

nomad_tls_enable: false
nomad_tls_ca_cert: ""
nomad_tls_cert: ""
nomad_tls_cert_key: ""

nomad_cli_profile_enabled: false
nomad_cli_tls_cert: ""
nomad_cli_tls_cert_key: ""

nomad_acl_enabled: false
nomad_acl_bootstrap_token_dest_path: "nomad-token"
