- name: "restart_influxdb_telegraf"
  become: true
  ansible.builtin.service:
    name: "influxdb_telegraf"
    state: "restarted"

- name: "reload_systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reexec: true
